project_id = "xiadarnexsajzdilesoc"

[functions.fetch-news]
verify_jwt = true

[functions.analyze-news]
verify_jwt = true

[functions.fetch-related-news]
verify_jwt = true

[functions.translate-article]
verify_jwt = true

[functions.ai-search-news]
verify_jwt = true

[functions.admin-get-users]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-get-access-requests]
verify_jwt = true

[functions.admin-reject-request]
verify_jwt = true
